
CREATE TABLE users (
   UID SERIAL PRIMARY KEY,
   NAME     TEXT    NOT NULL,
   PASSWD   TEXT    NOT NULL,
   JOINED TIMESTAMP   NOT NULL,  
   LAST_LOGIN TIMESTAMP
);

CREATE TABLE events (
   EVID SERIAL PRIMARY KEY,
   COOKIE   TEXT    NOT NULL,
   URL      TEXT    NOT NULL,
   TITLE     TEXT,
   CREATED  TIMESTAMP    NOT NULL  
);

CREATE TABLE browsers (
   BID SERIAL PRIMARY KEY,
   AGENT    TEXT,
   CREATED  TIMESTAMP    NOT NULL,  
   VISITED  TIMESTAMP    NOT NULL  
);

